### ISSUE TITLE
Registry Artifacts using key_value_pairs and wildcards fail to get results

### ISSUE THREAD

**Issue by pidydx** [google/grr#196]
Artifacts using wildcards in the key field does not work.
```
name: WindowsStubPaths
doc: Windows StubPath persistence.
sources:
- type: REGISTRY_VALUE
  attributes:
    key_value_pairs:
      - {key: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\*', value: 'StubPath'}
      - {key: 'HKEY_USERS\%%users.sid%%\Software\Microsoft\Active Setup\Installed Components\*', value: 'StubPath'}
supported_os: [Windows]
```

Artifact WindowsStubPaths data collection failed. Status: message GrrStatus { cpu_time_used : message CpuSeconds { system_cpu_time : 0.0 user_cpu_time : 0.0 } error_message : u"File not found: message PathSpec {\n path : u'*/StubPath'\n pathtype : TSK\n}" network_bytes_sent : 180 status : IOERROR }.

**Comment by scudette** [comment]
This is unfortunately an issue we have encountered often but we have no good solution to it. The main problem is that the keys are provided as a "file glob" but that concept is really not well defined at all!

For example if you tried to issue the following file glob in a linux machine you would not be at all surprised:

```
$ ls /tmp\*.exe
ls: cannot access /tmp*: No such file or directory
```

Since you have clearly escaped the * char with the backslash. On Windows this does not mean the same thing at all since \ is a path separator and the escaping capabilities are very weak. Since GRR has no idea what it is supposed to do - it follows the following rules:

1. forward slash is a path separator (it gets converted to the client's OS convention on the client but the server does not care).
2. Backslash is an escape character if it comes before wildcards otherwise it might be a path separator for windows (this is quite a confusing behaviour but its a compromise).

The above should work if you flip all backslash to forward slashes. We consider / to be the path separator and \ is only a windows compatible fallback which often causes more problems than helps - if you can train your users to always use / then you will have no problems.

**Comment by pidydx** [comment]
I tried flipping them or using the separator: declaration and neither seems to help.  If I convert it to a REGISTRY_KEY type and just use HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\*\StubPath it works properly.  However, I'm not sure if altering those and submitting them back to ForensicsArtifacts is right if they are technically REGISTRY_VALUE items.

It looks like this particular problem is isolated to how GRR is combining the key: and value: fields for REGISTRY_VALUE artifacts.

**Comment by pidydx** [comment]
I moved the wildcard further into the key string and it looks like it is just cutting off everything before the wildcard.
Rewriting it like this allows the artifact to work.
```
name: WindowsStubPaths
doc: Windows StubPath persistence.
sources:
- type: REGISTRY_KEY
  attributes:
    keys: 
      - 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\*\StubPath'}
      - 'HKEY_USERS\%%users.sid%%\Software\Microsoft\Active Setup\Installed Components\*\StubPath'}
supported_os: [Windows]
```
