### ISSUE TITLE
Add artifacts for firewall rules

### ISSUE THREAD

**Issue by destijl** [google/grr#330]
Like this as written by keith, except use the apple alf plist instead of the CLI (which seems to be missing information).

```
 Firewall Related Artifacts.

name: Firewalls
doc: Firewall Native to OS.
sources:
- type: REGISTRY_KEY
  attributes:
    keys:
      - 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\SharedAccess\Parameters\FirewallPolicy\FirewallRules'
  supported_os: [Windows]
- type: COMMAND
  attributes:
    args: ['-L', '-v', '-n']
    cmd: /sbin/iptables
  supported_os: [Linux]
- type: COMMAND
  attributes:
    args: ['--listapps']
    cmd: /usr/libexec/ApplicationFirewall/socketfilterfw
  supported_os: [Darwin]
labels: [System, Network]
supported_os: [Windows, Linux, Darwin]
```
